---
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members
  apiHost:
    Type: String
    Description: Api Gateway Host
  apiBasePath:
    Type: String
    Description: Api Gateway Base Path

Resources:
  DynamicDnsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ProjectId}-lambda
      Description: !Sub ${ProjectId} Lambda Function
      Handler: index.handler
      Runtime: python3.6
      CodeUri: ./
      Timeout: 15
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSSMReadOnlyAccess
        - AmazonRoute53FullAccess
        - AmazonAPIGatewayAdministrator

  DynamicDnsApi:
    Type: AWS::Serverless::Api
    DependsOn:
      - DynamicDnsLambda
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        info:
          version: "1.0"
          title: !Sub ${ProjectId}-api
        host: !Ref apiHost
        basePath: !Sub "/${apiBasePath}"
        schemes:
          - "https"
        paths:
          /:
            post:
              responses: {}
              security:
                - api_key: []
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DynamicDnsLambda.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
        securityDefinitions:
          api_key:
            type: "apiKey"
            name: "x-api-key"
            in: "header"
