---
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members
  apiHost:
    Type: String
    Description: Api Gateway Host
  apiBasePath:
    Type: String
    Description: Api Gateway Base Path

Resources:
  DynamicDnsWaitConditionHandle:
    Type: AWS::CloudFormation::WaitHandle

  DynamicDnsLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: Dynamic DNS
      Handler: index.handler
      Runtime: python3.6
      CodeUri: ./
      Timeout: 15
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSSMReadOnlyAccess
        - AmazonRoute53FullAccess
        - AmazonAPIGatewayAdministrator
          #      Events:
          #        PostEvent:
          #          Type: Api
          #          Properties:
          #            Path: /
          #            Method: post
          #            RestApiId: !Ref DynamicDnsApi

  DynamicDnsApiWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: DynamicDnsApi
    Properties:
      Handle: !Ref DynamicDnsWaitConditionHandle
      Timeout: 4500

  DynamicDnsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        info:
          version: "1.0"
          title: awscodestar-ddns-lambda
        host: !Ref apiHost
        basePath: !Sub "/${apiBasePath}"
        schemes:
          - "https"
        paths:
          /:
            post:
              responses: {}
              security:
                - api_key: []
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DynamicDnsLambda.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
        securityDefinitions:
          api_key:
            type: "apiKey"
            name: "x-api-key"
            in: "header"
    DependsOn: DynamicDnsLambda

  DynamicDnsMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref apiBasePath
      DomainName: !Ref apiHost
      RestApiId: !Ref DynamicDnsApi
      Stage: Prod
    DependsOn: DynamicDnsApiWaitCondition

  DynamicDnsUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: ddns
      ApiStages:
        - ApiId: !Ref DynamicDnsApi
          Stage: Prod
      Description: Dynamic DNS Usage Plan
      Quota:
        Limit: 500
        Period: DAY
      Throttle:
        BurstLimit: 20
        RateLimit: 10
    DependsOn: DynamicDnsApiWaitCondition
