---
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
Description: Python Webservice for Dynamic DNS

Parameters:
  ProjectId:
    Type: String
    Description: ProjectId used to associate resources
  apiHost:
    Type: String
    Description: Api Gateway Host
  apiBasePath:
    Type: String
    Description: Api Gateway Base Path

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ProjectId}-lambda
      Description: !Sub ${ProjectId} Lambda Function
      Handler: index.handler
      Runtime: python3.6
      CodeUri: ./
      Timeout: 15
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSSMReadOnlyAccess
        - AmazonRoute53FullAccess
        - AmazonAPIGatewayAdministrator
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref ApiGateway

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        info:
          version: "1.0"
          title: !Sub ${ProjectId}-api
        host: !Ref apiHost
        basePath: !Sub "/${apiBasePath}"
        schemes:
          - "https"
        paths:
          /:
            post:
              responses: {}
              security:
                - api_key: []
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ProjectId}-lambda/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
        securityDefinitions:
          api_key:
            type: "apiKey"
            name: "x-api-key"
            in: "header"

  ApiGatewayUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - ApiGateway
      - ApiGatewayProdStage
      - LambdaFunction
    Properties:
      UsagePlanName: !Ref ProjectId
      Description: !Sub ${ProjectId} usage plan
      Quota:
        Limit: 500
        Period: DAY
      Throttle:
        BurstLimit: 20
        RateLimit: 10
      ApiStages:
        - ApiId: !Ref ApiGateway
          Stage: Prod

  ApiGatewayMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn:
      - ApiGateway
      - ApiGatewayProdStage
      - LambdaFunction
    Properties:
      BasePath: !Ref apiBasePath
      DomainName: !Ref apiHost
      RestApiId: !Ref ApiGateway
      Stage: Prod
